<?xml version="1.0" encoding="utf-8"?><Database Name="CRMDB" Class="CRMDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone_call" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Email_ans" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Call_timing" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Open_Issue" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Communication_channel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Totalsale" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Return_cancellation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.user1" Member="user1s">
    <Type Name="user1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>